### ISSUE TITLE
DataTable not showing with development version of DT

### ISSUE THREAD

**Issue by enrico16** [rstudio/DT#182]
I have a Shiny app that works well with the DT  package on CRAN:

```
> library(DT)
> packageVersion("DT")
[1] ‘0.1’
```
![2015-09-17 11_17_12-clipboard](https://cloud.githubusercontent.com/assets/4481814/9930834/97cd85e8-5d2e-11e5-8951-76da8ffdfd1a.png)

However, I need to use the development version because of this issue:
[GitHub](https://github.com/rstudio/DT/issues/180)
[StackOverflow](http://stackoverflow.com/questions/32102855/shiny-datatable-rows-current-and-rows-all-give-the-same-rows)

When I use the development version, the DataTable just doesn't show up:

```
> library(DT)
> packageVersion("DT")
[1] ‘0.1.37’
```

![2015-09-17 11_27_15-clipboard](https://cloud.githubusercontent.com/assets/4481814/9930946/343b311e-5d2f-11e5-8521-8120bf40ec37.png)

I can't see any error message or anything and all other widgets work.
I'm working with big DataTables with more than 200K rows.

Any help is appreciated!
Thanks,

**Comment by yihui** [comment]
Sorry, but that is really too little information for me to think of anything to help you. What you may try to do is to reduce your app into a minimal reproducible example: replace real data with random numbers, remove all irrelevant parts in the UI (sliders, tab panels, ...), and so on.

**Comment by enrico16** [comment]
Got it, I will come back to you with a reproducible example (hopefully).

**Comment by enrico16** [comment]
OK, I've got a minimal reproducible example.

This runs fine on the DT version on CRAN (0.1) but no DataTable is displayed with the development version (0.1.37).

```
library(shiny)
library(DT)

set.seed(16)
mat <- matrix(rnorm(5e6, 100, 100), 5e5, 10)
dat <- as.data.frame(mat)

server <- function(input, output) {
    output$table <- DT::renderDataTable(dat, server=TRUE, rownames=TRUE, filter="top", options=list(pageLength=10))
}

ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(),
        mainPanel(DT::dataTableOutput("table"))
))

shinyApp(ui = ui, server = server)
```

Can you reproduce this?
I'm running this on a local instance of Shiny Server v1.3.0.403
Thanks!

**Comment by enrico16** [comment]
I can confirm the same behaviour with the latest version of shiny-server (1.4.0.721).

**Comment by yihui** [comment]
Yes I can reproduce it. Hmm, weird. I'll look into it. Thanks!

**Comment by yihui** [comment]
Okay, I think it should be fixed now. Thanks a lot for the report and more importantly, the reproducible example!

**Comment by shrektan** [comment]
Something that I can thing of is please ensure you call `library(DT)` after `library(shiny)`

**Comment by enrico16** [comment]
Great, my app also works now! Thank you for squashing the bug so quickly!

**Comment by aditya-kothari** [comment]
Hi the issue still persists as I am unable to view the databale using the devlopment version but I am able to view it in the CRAN version

**Comment by tsouchlarakis** [comment]
I can second that the issue still persists. I am not able to view the table in @enricoferrero's example with either the development version or version on CRAN.

**Comment by yihui** [comment]
@aditya-kothari @tsouchlarakis Could you open a new issue and provide a minimal reproducible example?
