### ISSUE TITLE
filter boxes supported?

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#22]
Are filter boxes below each column still supported? Even more interesting, is it possible to but a shiny input (e.g., slider or selectInput) above or below each column?

**Comment by yihui** [comment]
Yes, filters in the footer is probably the only thing left in shiny that has not been implemented in DT.

Regarding the second point, I guess the answer is yes, and it is something I imagined from day one. I will see what I can do. Thanks!

**Comment by mostly-harmless** [comment]
Thanks Yihui. You can, of course, just ask a user to type in a long filter statement. That is what I do now in my app with a textInput. It is easy to save and apply in other parts of an app. However, as an example of something that would be very convenient and useful for filtering see http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html. This has drag-and-drop functionality, which is nice as well, but the filtering options are perhaps most interesting. For each variable there is a drop-down with check-boxes (+ select all or select none) and an option to filter. Although the selected values are hidden here, a normal selectizeInput in Shiny would take up too much space when more than a few options are selected. For numeric variables a filter box and/or slider would be more useful. Having this type of filtering above/below each column would be very very useful.

FYI @timelyportfolio made a [binding to sortable.js](https://github.com/timelyportfolio/sortableR/blob/master/vignettes/QuickExample.Rmd#power-of-groups)

**Comment by bashyal** [comment]
+1 for adding column filters. Thanks for your work on DT.

**Comment by vnijs** [comment]
I will check it out soon. Thanks Yihui!

**Comment by yihui** [comment]
No problem. Please read the section "Column Filters" at http://rstudio.github.io/DT/ since the R help page  `?datatable` is very brief.

**Comment by vnijs** [comment]
The example at https://yihui.shinyapps.io/DT-filter/ is *really* nice!! Selecting factor levels is exactly what I was hoping for!! I did notice that manual editing works for numeric variables but does not seem to for dates. 




Question: I can be a bit tricky to set the sliders to exact values. If I wanted to add ‘> 2015’ as an option for dates or ‘< 20’ for numerics would this just be a custom function to process on the server-side or would something else be required?




Vincent


—

**Comment by yihui** [comment]
If you want the filter to be one-sided, you can leave the other side to be `null` in the box, e.g. if you type `null ... 20` in the box (hit Enter), it just means `<= 20`. Same thing for dates, e.g. `2015-01-01 ... null` means `>= 2015-01-01`. You cannot omit month and day in the date, though, since that is not a valid date.

**Comment by vnijs** [comment]
Got it. Manually changing the date from 2015-03-23 to 2015-03-25 doesn’t seem to work however. When I press enter the date is reset to 2015-03-23. Same thing for start and end dates.



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by yihui** [comment]
I think I just fixed this issue. The number of milliseconds for a date is on the order of 10^13, and the slider is not very good at handling such big numbers precisely.

**Comment by vnijs** [comment]
Nice. That works. Thanks!


—

**Comment by vnijs** [comment]
The udpated sliders look fantastic Yihui! Thanks. Planning to start using this soon!

**Comment by yihui** [comment]
@vnijs Thanks! I know there are still a few minor issues, but I'll just let you try and see if they will bother you enough :)

**Comment by vnijs** [comment]
@yihui a few comments

1. Interaction with DT (inside a shiny app) feels quite a bit slower than with the ‘old’ version. With a sample of 3000 from the diamonds data there is already a noticeable difference, e.g., in selecting and sorting variables. The effect is most pronounced when the filter boxes are shown. 
2. The sliders are very precise. This is nice but can also make it difficult to get to an exact value. I could manually input/changes when I have only a few columns. However, when I have 10 variables I cannot see or enter anything into the filter box. A related point, the sliders for integer variables allow filtering on decimals which seems unnecessary.
3. In your examples, selected levels do not take up extra space when you click outside the filter box. I installed the latest version (as of yesterday) and I see the regular selectize look.
4. With 10 columns the slider for the last column seems to be right-aligned on the 9th column

Just FYI, the settings I tried:

```
  DT::datatable(dat, rownames = FALSE, filter = 'bottom',
        options = list(pageLength = 10, autoWidth = TRUE, server = TRUE,
                       class = 'cell-border stripe',
                       lengthMenu = list(c(10, 25, 50, -1),c('10','25','50','All')))
  )
```

Thanks again for the work on DT!

**Comment by yihui** [comment]
Thanks for the feedback!

1. `server = TRUE` is _not_ an option in the `options` argument; it is an argument of `datatable()`, and must be used along with `options = list(ajax = list(url = ...))`. Please read `?datatable` carefully and also the examples: http://rstudio.github.io/DT/server.html
1. Yes, I can improve the sliders and use step length 1 when the column is integers. The spacing issue is trickier: when you have a large number of columns, each column has to have a tiny width, unless you put the table in a div that has a horizontal scroll bar.
1. Unfortunately I guess it is a bad idea to show all selected values in the box since the box will be too big and the UI will look ugly. If you want to know what were selected, you can simply mouse over the box, and you will see a tooltip. Same thing applies to sliders, as documented in Section 2.6: http://rstudio.github.io/DT/
1. I will try to adjust the position of the slider when it reaches beyond the right margin of the page. I guess the new position might be a little off in some cases.

**Comment by vnijs** [comment]
2. Do you have an example of a div with the horizontal scroll bar?
3. What I meant is that in your examples the box does *not* stay big. However, when I run DT it does stay big and shows all selected levels (see image below).

![image](https://cloud.githubusercontent.com/assets/2998956/7079652/c4eccff6-dedb-11e4-9ead-553a07d5b710.png)

For other variable types the hover-over works but I cannot get 'into' the box to edit the content manually when there are 10 or more columns. Perhaps reducing the padding for the boxes could help a bit as well (and/or option 1). Also, I noticed that you cannot use the arrow keys with these slider the way you can with the regular Shiny sliders. That might also help to get to exact numbers.

4. Thanks.

1. So server = TRUE is an option for datatable and serverSide = TRUE is an option for options. Got it.

For both options I get the error below when I try to view the table. The error does not show up when I take the server (or serverSide) option back out:

DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

New setup:

  DT::datatable(dat, rownames = FALSE, server = TRUE, filter = "bottom",
    options = list(
      columnDefs = list(list(className = 'dt-center', targets = "_all")),
      pageLength = 10,
      lengthMenu = list(c(10, 25, 50, -1),c('10','25','50','All'))
    )
  )

DT: 0.0.35
Shiny: 0.11.1
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

**Comment by vnijs** [comment]
Very minor point. After clicking on the filter box for factor-variables the boxes become smaller. See image.

![image](https://cloud.githubusercontent.com/assets/2998956/7080110/d2377ea8-dee1-11e4-833c-5179d278e3c2.png)

**Comment by yihui** [comment]
1. Are there error messages in the R console?
1. Yes, nothing fancy -- just straight CSS:

    ```r
    data(diamonds, package = 'ggplot2')
    library(shiny)
    library(DT)
    shinyApp(
      ui = fluidPage(
        fluidRow(
          column(
            4,
            div(DT::dataTableOutput('tbl'), style = 'width: 600px'),
            style = 'overflow-x: scroll'
          )
        )
      ),
      server = function(input, output, session) {
        output$tbl = DT::renderDataTable({
          datatable(head(diamonds, 100), filter = 'bottom')
        })
      }
    )
    ```

1. The select box shows all selected values only when it is on focus; when it loses focus, all selected values are collapsed into a text box.
  - When the number of columns is big, perhaps I should just hide the clear buttons...

**Comment by vnijs** [comment]
1. No errors in the R console. I get the error when I add server = TRUE to your example as well (see below). The same error message in the browser occurs on Windows and on Mac.

2. Hmm. I will have to see how that would work with a tabPanel. 

3. That is what it does in your examples. It doesn't work in my app (see the picture I posted earlier). I did notice, however, that it works in the example you sent. I guess there is an interactions somewhere. Bummer.

4. Hiding the clear button might be an option. However, how would you then know that a filter is active for a column?

```
data(diamonds, package = 'ggplot2')
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    fluidRow(
      column(
        4,
        div(DT::dataTableOutput('tbl'), style = 'width: 600px'),
        style = 'overflow-x: scroll'
      )
    )
  ),
  server = function(input, output, session) {
    output$tbl = DT::renderDataTable({
      datatable(head(diamonds, 100), server = TRUE, filter = 'bottom')
    })
  }
)
```

**Comment by yihui** [comment]
For 1, you have to read my reply in the very beginning again: https://github.com/rstudio/DT/issues/22#issuecomment-91379044 Simply adding `server = TRUE` won't work.

For 4, you know a filter is active when there are values in the text boxes.

**Comment by vnijs** [comment]
1. Got it working! Sorry about the mix-up.
4. When the boxes get smaller no text is visible. If this is just because it is being blocked by the clear button then your idea should work. 

I just updated radiant to use DT. With shiny-server and linux I am also seeing the issue mentioned in [3] above. See the Data > View tab in the app linked below. 

http://vnijs.rady.ucsd.edu:3838/marketing

If you try the link below you should see the variables I selected in my session (i.e., price - color):

http://vnijs.rady.ucsd.edu:3838/marketing/?SSUID=de0468cd6371c1ce6c0022de26a0d4d6

**Comment by yihui** [comment]
I see what you meant now and figured out the reason, but it looks a little tricky to fix it. I'll think about it tomorrow. It is a clash between shiny's selectize input and DT's.

**Comment by vnijs** [comment]
Tanks for looking into this Yihui! Could DT's selectize feature perhaps be added to Shiny? Would be a nice option to have.

**Comment by vnijs** [comment]
I just noticed that if you enter a search term that is not found you get an 'invalide JSON response' warning from DataTables. Same applies if you select a factor level that is not in the sub-set of data that was already filtered.

**Comment by yihui** [comment]
@vnijs I believe the selectize issue should be solved now.

**Comment by vnijs** [comment]
Works! Thanks Yihui!

**Comment by vnijs** [comment]
Unfortunately smartinsightsfromdata/rpivotTable (@smartinsightsfromdata) stopped working with the latest versions of:

devtools::install_github("vnijs/radiant")
devtools::install_github(c("smartinsightsfromdata/rpivotTable","trestletech/shinyAce"))
devtools::install_github(c('jeroenooms/jsonlite', 'rstudio/shiny', 'ramnathv/htmlwidgets'))
devtools::install_github('rstudio/shiny', 'ramnathv/htmlwidgets'))
devtools::install_github(c("rstudio/DT"))

You can see the effect when you try to try dragging-and-dropping variables in the Data > Pivot tab at :
https://vnijs.shinyapps.io/marketing/

Also, on windows I'm getting a permission issue when installing jsonlite from GitHub:

installing to C:/Users/vnijs/Documents/R/win-library/3.1/jsonlite/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\jsonlite.dll to C:\Users\vnijs\Documents\R\win-library\3.1\jsonlite\libs\x64\jsonlite.dll: Permission denied
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
Error in FUN(structure(c("C_collapse_array", "C_collapse_array_pretty_inner",  : 
  no such symbol C_collapse_array_pretty_inner in package C:/Users/vnijs/Documents/R/win-library/3.1/jsonlite/libs/x64/jsonlite.dll
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
* removing 'C:/Users/vnijs/Documents/R/win-library/3.1/jsonlite'

**Comment by yihui** [comment]
I suggest you restart R before you install jsonlite, or even reboot your computer.

**Comment by vnijs** [comment]
OK. That helped to get jsonlite installed on Windows. Thanks. rpivotTable still broken though (mac, shinyapps.io, windows)

**Comment by smartinsightsfromdata** [comment]
This has been now clarified.
