### ISSUE TITLE
DT hanging with shiny/flexdashboard

### ISSUE THREAD

**Issue by delta8** [rstudio/DT#718]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by delta8** [comment]
Hi,
I'm trying to use DT in R Markdown Shiny/Flexdashboard but it seems to be hanging.  I have used this before and it worked GREAT--but even in my older programs, the document is not rendering.  Please see my example code below-it's not in great format:

`---
  title: "Testing DT and Shiny and FlexDashboard"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
  vertical_layout: scroll
orientation: rows 
theme: "cosmo"
---
  
  ```{r Required Libraries, include=FALSE}
library(flexdashboard)
library(shiny)
library(plyr)
library(dplyr)
library(tidyverse)
library(DT)
```


Row
-------------------------------------
  ### **Table 1: Render Table Works **
  
  ```{r Table w/o DT, echo=FALSE}
data("mtcars")

renderTable(head(mtcars))
```

Row
-------------------------------------
  ### **Table 2: Render DT::DataTable Does NOT work **
  
  ```{r Table w/ DT, eval=FALSE, include=FALSE}
data("mtcars")

renderDataTable(head(mtcars))
```


`

**Comment by yihui** [comment]
> it's not in great format

Please read the issue guide.

**Comment by delta8** [comment]
I updated my code above:  

```
---
  title: "Testing DT and Shiny and FlexDashboard"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
  vertical_layout: scroll
orientation: rows 
theme: "cosmo"
---
  
  ```{r Required Libraries, include=FALSE}
library(flexdashboard)
library(shiny)
library(plyr)
library(dplyr)
library(tidyverse)
library(DT)
```

  ### **Table 1: Render Table Works **
  
  ```{r Table w/o DT, echo=FALSE}
data("mtcars")

renderTable(head(mtcars))
```


  ### **Table 2: Render DT::DataTable Does NOT work **
  
  ```{r Table w/ DT, eval=FALSE, include=FALSE}
data("mtcars")

renderDataTable(head(mtcars))
```

**Comment by shrektan** [comment]
Well, it works on my computer. Please upgrade your packages and test it again. If the issue still exists, please re-read the issue guide and paste your version info. Thanks.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/8368933/66409287-f7482980-ea22-11e9-986c-9331cb7e5429.png">

**Comment by delta8** [comment]
Thanks--I *thought* I did update all my packages, thanks for the reminder!  I do now see it works, htmlwidgets wasn't updated.  

Thank you for your time--sometimes it's helpful to know it DOES work and it's on my end!  
Rhonda

**Comment by yihui** [comment]
@delta8 You still didn't really the issue guide carefully. 1) The issue guide asked you to update packages before reporting issues, and provide session info. 2) The issue guide also told you how to format your issue correctly (in particular, the four-backtick rule), and your examples were still not correctly formatted. Please take your promises above more seriously in the future when you check the boxes. Thank you!
